### ISSUE TITLE
feature: use ulixee/hero instead of puppeteer-extra as the headless browser solution

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/firecrawl-simple#13]
Puppeteer-extra has not been maintained for over a year and is easily detected in present day. Headless steal browser solution should be swapped to https://github.com/ulixee/hero in order to maximize stealthiness. 

[initializeBrowser in apps/puppeteer-service-ts/api.ts](https://github.com/devflowinc/firecrawl-simple/blob/main/apps/puppeteer-service-ts/api.ts#L35-L65) needs to be modified to use hero.

**Comment by yacineA** [comment]
hi @skeptrunedev  is this still available ? can you assign it to me ?
/attempt #13

**Comment by daveads** [comment]
> hi @skeptrunedev is this still available ? can you assign it to me ? /attempt #13

kinda already solved this.
